/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.spica.plugin.gradle.jacoco.example;

import java.lang.invoke.MethodHandles;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

  private static final Logger LOGGER = LoggerFactory
      .getLogger(MethodHandles.lookup().lookupClass());

  public String getGreeting(
      String[] args
  ) {
    if (args.length == 0) {
      return "Hello world.";
    } else if (args.length == 1) {
      return "Hello world!.";
    } else {
      return "Hello world!!.";
    }
  }

  public static void main(String[] args) {
    LOGGER.atInfo()
        .setMessage("{}")
        .addArgument(() -> new App().getGreeting(args));
  }
}
