/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.spica.plugin.gradle.jacoco.example;

public class App {

  public String getGreeting(
      String[] args
  ) {
    if (args.length == 0) {
      return "Hello world.";
    } else if (args.length == 1) {
      return "Hello world!.";
    } else {
      return "Hello world!!.";
    }
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting(args));
  }
}
