/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.spica.plugin.gradle.jacoco;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'jp.gr.java_conf.spica.plugin.gradle.jacoco.greeting' plugin.
 */
public class JacocoMarkdownPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("jp.gr.java_conf.spica.plugin.gradle.jacoco.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
