/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.gr.java_conf.spica.plugin.gradle.jacoco.example;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(new String[]{}), "app should have a greeting");
  }

  @Test
  void appHasAGreetingWith1Arg() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(new String[]{"a"}), "app should have a greeting!.");
  }

  @Test
  void appHasAGreetingWith2Arg() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(new String[]{"a", "b"}),
        "app should have a greeting!!.");
  }
}
