# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gradle binary cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper/
          key: gradle-wrapper-${{ hashFiles('plugin/src/functionalTest/resources/gradleVersions.csv') }}
          restore-keys: |
            gradle-wrapper-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          # Gradle 9 supports JDK17 or later.
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: plugin/build/reports/jacoco/test/jacocoTestReport.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: plugin/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
